### ISSUE TITLE
shimcode , shim 명칭 변경

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/tesseract#2]

**Comment by hackurity01** [comment]
cellCode
prismCode
cubeCode
projectionCode
등이 있는데,

shim의 역할이 SmartContract가 실행될 수 있도록 환경을 구성해주는데에 있으니   
테서렉트 구성요소인 cell을 따서 **cellCode, cell** 이라고 변경하면 좋을거 같습니다.

**Comment by junbeomlee** [comment]
좋은 아이디어인것 같습니다. 이름 바꿔서 풀리퀘 보내주세요!
