### ISSUE TITLE
[icode log] icode의 내부 log를 볼수 있도록

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/tesseract#28]
아직 어떻게 할지 구체적으로 정한거 아니지만 대안2개
1. log파일을 volume해서 engine쪽에서 cat할 수 있게 한다
2. elastic search를 띄운후에 icode내에서 log파일을 es로 보내서 9200번 포트로 확인가능하게 한다.

정도가 있습니다.
1번은 log파일 공유
2번은 log파일을 es로 공유

**Comment by zeroFruit** [comment]
@zeroFruit

**Comment by zeroFruit** [comment]
/logs/icode_<icode name> 으로 bind mount.
icode 내에서 logger로 icode.log로 로그를 찍으면 bind mount한 폴더에서 보인다.
