### ISSUE TITLE
[docker] remove all containers before run test

### ISSUE THREAD

**Issue by zeroFruit** [it-chain/tesseract#35]
돌아가는 컨테이너가 남아있으니 getAvailablePort가 제대로 동작하지 않는 것 같습니다.

![image](https://user-images.githubusercontent.com/18715362/43883296-93cd611a-9bed-11e8-9a79-3c179174697e.png)

**Comment by hea9549** [comment]
이건 getAvailabelPort가 잘 작동하지 않는것이아니라 테스트코드의 문제같습니다!

컨테이너가이미 50010까지 돌고있어서
getAvailablePort는 50011을 가져오는데 
테스트에서는 50001로 하드코딩 되있어서 문제입니다!

테스트 코드앞부분에 모두 컨테이너를 닫던지 아니면 포트번호를 받아오던지 해야할것같습니다!

근데 형 언제와여 배고파여 ㅜㅜ

**Comment by hea9549** [comment]
잉아닌가 형 왜 10개떠잇어여?

**Comment by hea9549** [comment]
아 맞네여 테스트케이스 잘못임 ㅇㅇ actual 이랑 expect랑 반대로 써져잇어서 햇갈렷음
